# Generated by Django 5.1.6 on 2025-05-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0005_remove_medication_dosage_remove_medication_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medication",
            name="user",
        ),
        migrations.RemoveField(
            model_name="medicationlog",
            name="medication",
        ),
        migrations.DeleteModel(
            name="MedicationTime",
        ),
        migrations.DeleteModel(
            name="Medication",
        ),
        migrations.DeleteModel(
            name="MedicationLog",
        ),
    ]
