# Generated by Django 5.1.6 on 2025-03-24 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_newslettersubscriber"),
    ]

    operations = [
        migrations.CreateModel(
            name="FIR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crime_type",
                    models.CharField(
                        choices=[("Cyber", "Cyber"), ("Physical", "Physical")],
                        max_length=10,
                    ),
                ),
                (
                    "crime_category",
                    models.CharField(
                        choices=[
                            ("Robbery", "Robbery"),
                            ("Molestation", "Molestation"),
                            ("Fraud", "Fraud"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("other_crime", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField()),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("citizenship", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
