# Generated by Django 5.1.6 on 2025-03-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0003_fir"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="customuser_permissions_set",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
