# Generated by Django 5.1.6 on 2025-03-25 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_customuser_user_permissions"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fir",
            old_name="crime_category",
            new_name="crime_name",
        ),
        migrations.RemoveField(
            model_name="fir",
            name="other_crime",
        ),
    ]
