# Generated by Django 5.1.6 on 2025-03-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SleepDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('symptoms', models.TextField()),
                ('diagnosis_result', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
